services:
  backend:
    build: .
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules # Compatibilidade com mac e windows (Desvantagem: precisa buildar sempre que baixar nova dependência)
      # Comente a linha acima caso use linux
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: [ "postgres", "-c", "port=${POSTGRES_PORT}" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
