name: API - Denuncias - CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check
        run: npx tsc --noEmit

      - name: Syntax check
        run: |
          find src -type f \(-name "*.js" \) \
          | xargs -I {} node --check {}

      - name: Validate Prisma schema
        run: npx prisma validate
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/dbname"

      - name: Run push-only step
        if: github.event_name == 'push'
        run: echo "This runs only on push!"

      - name: Run PR-only step
        if: github.event_name == 'pull_request'
        run: echo "This runs only on pull request!"

      - name: Configurar Docker Buildx (local)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Construir a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: plataforma-civica-backend:latest

      - name: Verificar se o contêiner sobe e está saudável
        run: |
          docker run -d --name my-backend -p 3000:3000 plataforma-civica-backend:latest

          echo "Aguardando 10 segundos para o contêiner inicializar..."
          sleep 10

          echo "Verificando o status do contêiner..."
          STATUS=$(docker ps -f name=my-backend --format "{{.Status}}")

          if echo "$STATUS" | grep -q "Up"; then
            echo "Contêiner 'my-backend' subiu com sucesso! Status: $STATUS"
          else
            echo "ERRO: Contêiner 'my-backend' não subiu corretamente. Status: $STATUS"
            docker logs my-backend
            exit 1
          fi
          docker stop my-backend && docker rm my-backend

  publish:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da imagem para GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}